'use client'
import { kwhToCarbon, kwhToCarbonCredits, kwhToMoneyINR, kwhToTrees } from '@/lib/solar'

const KWH = 3440.8

export default function ESGPage() {
  const carbon = kwhToCarbon(KWH)
  const trees = kwhToTrees(KWH)
  const ccc = kwhToCarbonCredits(KWH)
  const money = kwhToMoneyINR(KWH)

  const download = () => {
    const d = new Date().toLocaleDateString('en-IN')
    const txt = `ENERX — ESG VERIFIED REPORT\n===========================\nDate: ${d}\nFramework: SEBI BRSR 2024 / BEE CCTS 2023\nCarbon Factor: 0.82 kg CO₂/kWh (CEA 2023)\n\nTotal Generation: ${KWH.toFixed(2)} kWh\nCO₂ Offset: ${carbon} kg\nCarbon Credits: ${ccc.toFixed(4)} CCC\nMarket Value: ₹${money.toFixed(2)}\nTrees Equivalent: ${trees}\n\nGenerated by EnerX — energx.in`
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([txt],{type:'text/plain'}))
    a.download = `EnerX_ESG_${d.replace(/\//g,'-')}.txt`
    a.click()
  }

  const s = (extra={}) => ({background:'#fff',border:'1px solid rgba(44,36,23,0.1)',borderRadius:'18px',padding:'24px',...extra})
  const lbl = (t:string) => <div style={{fontSize:'11px',fontWeight:600,letterSpacing:'2px',textTransform:'uppercase' as const,color:'#8A7D6B',marginBottom:'10px'}}>{t}</div>

  return (
    <div style={{fontFamily:"'DM Sans',system-ui,sans-serif"}}>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:'28px'}}>
        <div>
          <h1 style={{fontFamily:"'Fraunces',Georgia,serif",fontSize:'26px',fontWeight:600,color:'#2C2417',letterSpacing:'-0.5px'}}>ESG Report</h1>
          <p style={{fontSize:'13px',color:'#8A7D6B',marginTop:'3px'}}>SEBI BRSR & BEE CCTS aligned verified data</p>
        </div>
        <div style={{display:'flex',alignItems:'center',gap:'6px',background:'#EAF0EA',border:'1px solid rgba(90,122,90,0.2)',borderRadius:'100px',padding:'8px 16px',fontSize:'12px',fontWeight:500,color:'#3D5C3D'}}>✓ BRSR Compliant</div>
      </div>

      {/* Key metrics */}
      <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:'16px',marginBottom:'20px'}}>
        {[
          {l:'Renewable Generated',v:`${KWH.toFixed(1)} kWh`,c:'#3D5C3D'},
          {l:'CO₂ Offset',v:`${carbon} kg`,c:'#5A7A5A'},
          {l:'Trees Equivalent',v:`${trees} trees`,c:'#D4860A'},
          {l:'BRSR Score',v:'A+',c:'#4A7FA5'},
        ].map(m=>(
          <div key={m.l} style={s()}>
            {lbl(m.l)}
            <div style={{fontFamily:"'Fraunces',Georgia,serif",fontSize:'26px',fontWeight:600,color:m.c}}>{m.v}</div>
          </div>
        ))}
      </div>

      {/* Carbon credits */}
      <div style={{...s({background:'linear-gradient(135deg,#EAF0EA,#fff)',border:'1px solid rgba(90,122,90,0.2)'}),marginBottom:'20px'}}>
        {lbl('Carbon Credit Analysis — BEE CCTS 2023')}
        <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:'20px'}}>
          {[
            {l:'Carbon Credits Earned',v:ccc.toFixed(4),u:'CCC',d:'1 CCC = 1 tonne CO₂'},
            {l:'Market Rate',v:'₹900',u:'/CCC',d:'Govt CCTS 2023 avg rate'},
            {l:'Total Value',v:`₹${money.toFixed(2)}`,u:'',d:'Tradeable in voluntary market'},
          ].map(item=>(
            <div key={item.l} style={{background:'#fff',borderRadius:'14px',padding:'20px',border:'1px solid rgba(44,36,23,0.07)',textAlign:'center'}}>
              <div style={{fontSize:'12px',color:'#8A7D6B',marginBottom:'8px'}}>{item.l}</div>
              <div style={{fontFamily:"'Fraunces',Georgia,serif",fontSize:'24px',fontWeight:600,color:'#3D5C3D'}}>{item.v}<span style={{fontSize:'13px',color:'#8A7D6B'}}>{item.u}</span></div>
              <div style={{fontSize:'11px',color:'#8A7D6B',marginTop:'4px'}}>{item.d}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Progress bars */}
      <div style={{...s(),marginBottom:'20px'}}>
        {lbl('Environmental Impact')}
        {[
          {l:'Renewable Energy Share',v:100,c:'#5A7A5A'},
          {l:'Carbon Intensity Reduction',v:82,c:'#3D5C3D'},
          {l:'Grid Independence',v:67,c:'#D4860A'},
          {l:'BRSR Compliance Score',v:95,c:'#4A7FA5'},
        ].map(item=>(
          <div key={item.l} style={{marginBottom:'16px'}}>
            <div style={{display:'flex',justifyContent:'space-between',fontSize:'13px',marginBottom:'8px'}}>
              <span style={{color:'#4A3F2F',fontWeight:500}}>{item.l}</span>
              <span style={{color:item.c,fontWeight:600}}>{item.v}%</span>
            </div>
            <div style={{height:'6px',background:'#EDE8DE',borderRadius:'3px',overflow:'hidden'}}>
              <div style={{height:'100%',width:`${item.v}%`,background:item.c,borderRadius:'3px',transition:'width 0.8s ease'}} />
            </div>
          </div>
        ))}
      </div>

      {/* Download */}
      <div style={{...s({background:'#fff',border:'1px solid rgba(44,36,23,0.1)'}),display:'flex',alignItems:'center',justifyContent:'space-between'}}>
        <div>
          <div style={{fontWeight:600,color:'#2C2417',marginBottom:'4px'}}>Download Full ESG Report</div>
          <div style={{fontSize:'13px',color:'#8A7D6B'}}>SEBI BRSR compliant · Auditable · Ready for corporate submission</div>
        </div>
        <button onClick={download} style={{padding:'12px 24px',background:'#5A7A5A',color:'#fff',border:'none',borderRadius:'100px',fontSize:'14px',fontWeight:500,cursor:'pointer',whiteSpace:'nowrap'}}>📄 Download Report</button>
      </div>
    </div>
  )
}
