'use client'
import { kwhToCarbon, kwhToCarbonCredits, kwhToMoneyINR } from '@/lib/solar'

const REPORTS = [
  { id:'R-001', title:'Q1 2026 ESG Report', period:'Jan–Mar 2026', kwh:8240.6, households:47, status:'ready' },
  { id:'R-002', title:'February 2026 Monthly', period:'February 2026', kwh:2680.2, households:47, status:'ready' },
  { id:'R-003', title:'March 2026 Monthly', period:'March 2026', kwh:2920.4, households:47, status:'ready' },
  { id:'R-004', title:'Q2 2026 ESG Report', period:'Apr–Jun 2026', kwh:0, households:47, status:'pending' },
]

function downloadReport(r: typeof REPORTS[0]) {
  const d = new Date().toLocaleDateString('en-IN')
  const txt = `ENERX — CORPORATE ESG REPORT\n=============================\nReport ID: ${r.id}\nPeriod: ${r.period}\nDate: ${d}\nCompany: Tata Motors Ltd\nFramework: SEBI BRSR 2024 / BEE CCTS 2023\n\nTotal Generation: ${r.kwh.toFixed(2)} kWh\nActive Households: ${r.households}\nCO₂ Offset: ${kwhToCarbon(r.kwh)} kg\nCarbon Credits: ${kwhToCarbonCredits(r.kwh).toFixed(4)} CCC\nMarket Value: ₹${kwhToMoneyINR(r.kwh).toFixed(2)}\n\nGenerated by EnerX — energx.in`
  const a = document.createElement('a')
  a.href = URL.createObjectURL(new Blob([txt],{type:'text/plain'}))
  a.download = `EnerX_${r.id}_${r.period.replace(/\s/g,'_')}.txt`
  a.click()
}

const s = (extra={}) => ({ background:'#fff', border:'1px solid rgba(44,36,23,0.1)', borderRadius:'18px', padding:'24px', ...extra })

export default function ReportsPage() {
  return (
    <div style={{ fontFamily:"'DM Sans',system-ui,sans-serif" }}>
      <div style={{ marginBottom:'28px' }}>
        <h1 style={{ fontFamily:"'Fraunces',Georgia,serif", fontSize:'26px', fontWeight:600, color:'#2C2417', letterSpacing:'-0.5px' }}>ESG Reports</h1>
        <p style={{ fontSize:'13px', color:'#8A7D6B', marginTop:'3px' }}>Download verified reports for SEBI BRSR filing</p>
      </div>

      <div style={{ display:'flex', flexDirection:'column', gap:'14px', marginBottom:'20px' }}>
        {REPORTS.map(r => (
          <div key={r.id} style={{ ...s(), display:'flex', alignItems:'center', gap:'16px' }}>
            <div style={{ width:'48px', height:'48px', background:r.status==='ready'?'#EAF0EA':'#F7F4EE', border:`1px solid ${r.status==='ready'?'rgba(90,122,90,0.2)':'rgba(44,36,23,0.1)'}`, borderRadius:'14px', display:'flex', alignItems:'center', justifyContent:'center', fontSize:'22px', flexShrink:0 }}>
              📄
            </div>
            <div style={{ flex:1 }}>
              <div style={{ fontWeight:600, color:'#2C2417', marginBottom:'3px' }}>{r.title}</div>
              <div style={{ fontSize:'12px', color:'#8A7D6B' }}>{r.period} · {r.households} households</div>
            </div>
            {r.status === 'ready' && (
              <div style={{ display:'flex', gap:'24px', marginRight:'16px' }}>
                {[
                  { label:'Generation', val:`${r.kwh.toFixed(1)} kWh`, color:'#5A7A5A' },
                  { label:'CO₂ Offset', val:`${kwhToCarbon(r.kwh)} kg`, color:'#3D5C3D' },
                  { label:'Value', val:`₹${kwhToMoneyINR(r.kwh).toFixed(0)}`, color:'#D4860A' },
                ].map(item => (
                  <div key={item.label} style={{ textAlign:'center' }}>
                    <div style={{ fontSize:'11px', color:'#8A7D6B', marginBottom:'2px' }}>{item.label}</div>
                    <div style={{ fontFamily:"'Fraunces',Georgia,serif", fontSize:'15px', fontWeight:600, color:item.color }}>{item.val}</div>
                  </div>
                ))}
              </div>
            )}
            {r.status === 'ready' ? (
              <button onClick={()=>downloadReport(r)} style={{ padding:'10px 20px', background:'#5A7A5A', color:'#fff', border:'none', borderRadius:'100px', fontSize:'13px', fontWeight:500, cursor:'pointer', whiteSpace:'nowrap' }}>
                ↓ Download
              </button>
            ) : (
              <div style={{ padding:'10px 20px', background:'#F7F4EE', borderRadius:'100px', fontSize:'13px', color:'#8A7D6B', whiteSpace:'nowrap' }}>
                Generating…
              </div>
            )}
          </div>
        ))}
      </div>

      <div style={{ ...s({ background:'#EAF0EA', border:'1px solid rgba(90,122,90,0.2)' }), display:'flex', alignItems:'center', gap:'14px' }}>
        <span style={{ fontSize:'22px' }}>✅</span>
        <div>
          <div style={{ fontWeight:600, color:'#2C2417', marginBottom:'3px' }}>All reports are SEBI BRSR compliant</div>
          <div style={{ fontSize:'13px', color:'#6B5D48', lineHeight:1.6 }}>Data is timestamped, auditable, and verified using CEA India 2023 emission factors. Suitable for annual ESG filing and third-party audit.</div>
        </div>
      </div>
    </div>
  )
}
